trigger:
  - master
stages:
- stage: FixTags
  jobs:
  - job: fixTags_build
    displayName: 'Fix Tags Internal'
    pool:
      vmImage: windows-latest

    workspace:
      clean: all
    
    steps:
      - checkout: none
        clean: true

      - task: NodeTool@0
        displayName: 'Use Node 14.16.0'
        inputs:
          versionSpec: 14.16.0

      - bash: |
          npm config set registry=https://devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/                 
          npm config set always-auth=true
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:username=Devops0187
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:_password=$(token)
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:email="not used"
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:username=Devops0187
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:_password=$(token)
          npm config set //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:email="not used"
        displayName: 'Seed npmrc'

      - script: |
         npm view $(packageName) dist-tags --json
        displayName: 'Old Dist Tags'

      - script: |
         npm dist-tag add $(packageName)@$(version) $(tag)
        displayName: 'Update Tags'

      - script: |
         npm view $(packageName) dist-tags --json
        displayName: 'New Dist Tags'
