trigger:
  - master
stages:
- stage: FixTags
  jobs:
  - job: fixTags_build
    displayName: 'Fix Tags Internal'
    pool:
      vmImage: windows-latest

    workspace:
      clean: all
    
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 14.16.0'
        inputs:
          versionSpec: 14.16.0
      - checkout: none
        clean: true

      - bash: |
          registry=https://devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/                 
          always-auth=true
          ; begin auth token
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:username=Devops0187
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:_password=$(token)
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/registry/:email=npm requires email to be set but doesn't use the value
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:username=Devops0187
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:_password=$(token)
          //devops0187.pkgs.visualstudio.com/_packaging/test/npm/:email=npm requires email to be set but doesn't use the value
          ; end auth token
        displayName: 'Seed npmrc'

      - script: |
         npm view $(packageName) dist-tags --json
        displayName: 'Current Dist Tags'
