trigger:
  branches:
    include:
      - master
  paths:
    include:
      - tools/*

pr:
  drafts: false
  branches:
    include:
      - master
  # paths:
  #   include:
  #     - tools/*

workspace:
  clean: all

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 14.16.0'
  inputs:
    versionSpec: 14.16.0

- checkout: self
  clean: true

- task: CmdLine@2
  displayName: 'NPM CONFIGURATION'
  inputs:
    script: 'npm config list' 

- script: npm install
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Schema Package Generation Tests'
  inputs:
    command: custom
    customCommand: run testPkgGen

- task: Npm@1
  displayName: 'Schema Inventory Generation Tests'
  inputs:
    command: custom
    customCommand: run testInvGen

- task: Npm@1
  displayName: 'Schema Comparison Tests'
  inputs:
    command: custom
    customCommand: run testSchemaDifference
    
- task: PowerShell@2
  condition: and(succeeded(), not(canceled()), startsWith(variables['Build.SourceBranchName'], 'io-build-retention'))
  name: RetainTagBuildsOnSuccess
  displayName: Retain Tag Builds on Success
  inputs:
    failOnStderr: true
    targetType: 'inline'
    script: |
      $contentType = "application/json";
      $headers = @{ Authorization = 'Bearer $(System.AccessToken)' };
      $rawRequest = @{ daysValid = 15 * 2; definitionId = $(System.DefinitionId); ownerId = 'User:$(Build.RequestedForId)'; protectPipeline = $false; runId = $(Build.BuildId) };
      $request = ConvertTo-Json @($rawRequest);
      $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/build/retention/leases?api-version=6.0-preview.1";
      Invoke-RestMethod -uri $uri -method POST -Headers $headers -ContentType $contentType -Body $request;
 
